import { webkit, devices } from "playwright";
const out = "docs/v4/shots/r2-insights";
const b = await webkit.launch();
const ctx = await b.newContext({ ...devices["iPhone 15 Pro"], reducedMotion: "reduce" });
const p = await ctx.newPage();
await p.goto("http://localhost:3106/insights/capacity-is-a-research-problem", { waitUntil: "load", timeout: 60000 });
await p.waitForTimeout(600);
const overflow = await p.evaluate(() => document.documentElement.scrollWidth - window.innerWidth);
console.log(`article 393: overflow=${overflow}px`);
await p.screenshot({ path: `${out}/article--393--fold.png` });
const statementSection = p.locator("p:has-text('Nobody lies; the number simply drifts')").last();
await statementSection.scrollIntoViewIfNeeded();
await p.waitForTimeout(150);
await p.screenshot({ path: `${out}/article--393--quote.png` });
await b.close();
